# url.py
URLS = [
            #NTA
            "https://neet.nta.nic.in/public-notices/",
            "https://neet.nta.nic.in/examination-schedule/",
            #Neet
            "https://natboard.edu.in/allnotice.php",
            #SSC
            "https://ssc.gov.in/home/notice-board",
            #Sikkim
            "https://spsc.sikkim.gov.in/Advertisement.html",
            "spsc.sikkim.gov.in/Notices.html",
            "https://www.sikkim.gov.in/media/employment-news",
            "https://hcs.gov.in/hcs/recruitment",
            #Tamilnadu
            "https://tnpsc.gov.in/english/notification.aspx",
            "https://www.tnpsc.gov.in/english/latest_results.aspx",
            #Telangana
            "https://websitenew.tspsc.gov.in/notifications",
            "https://websitenew.tspsc.gov.in/Results",
            "https://websitenew.tspsc.gov.in/GOS.jsp",
            "https://mhsrb.telangana.gov.in/MHSRB/home.htm",
            "https://tshc.gov.in/showChildDocTypes?id=95",
            #Nagaland
            "https://npsc.nagaland.gov.in/notification",
            "https://npsc.nagaland.gov.in/latest-updates",
            "https://dpar.nagaland.gov.in/notifications/",
            #Odisha
            "https://odisha.gov.in/publication/advertisement",
            "https://www.ossc.gov.in/Public/Pages/View_Content.aspx?id=MeNGKau42B9VX4Nn6oZfXA==",
            #Jharkhand
            "https://www.jpsc.gov.in/Examination-Links.php",
            "https://ranchi.nic.in/notice_category/recruitment/",
            "https://www.sameti.org/vaccancy.php",
            "https://sahibganj.nic.in/notice_category/recruitment/",
            "https://giridih.nic.in/notice_category/recruitment/",
            #karnatak
            "https://kpsc.kar.nic.in/",
            #Keral
            "https://www.keralapsc.gov.in/notifications",
            "https://jobs.kpesrb.kerala.gov.in/index.php/LatestNotifications",
            "https://cmd.kerala.gov.in/recruitment/",
            #Meghalaya
            "https://mpsc.nic.in/advertisements.html",
            "https://mpsc.nic.in/results.html",
            "https://mpsc.nic.in/advertisements.html",
            "https://mpsc.nic.in/news_announcements.html",
            "https://meghalaya.gov.in/recruitment",
            "https://megrecruitment.nic.in/rpa/login.htm",
            #Tripura
            "https://tripura.gov.in/recruitments",
            "https://health.tripura.gov.in/jobs-and-recruitment",
            "https://tpsc.tripura.gov.in/calendar",
            "https://tpsc.tripura.gov.in/content/all-documents",
            "https://tpsc.tripura.gov.in/examdb",
            "https://tpsc.tripura.gov.in/",
            "https://tpsc.tripura.gov.in/akey",
            "https://tpsc.tripura.gov.in/admit_card",
            "https://tpsc.tripura.gov.in/notifications",
            "http://www.jrbtripura.com/#/",
            #West Bengal
            "https://psc.wb.gov.in/whats_new.jsp",
            "https://psc.wb.gov.in/notification_announcement.jsp",
            "https://psc.wb.gov.in/advertisement.jsp",
            "https://psc.wb.gov.in/answer_key.jsp",
            "https://psc.wb.gov.in/results.jsp",
            "https://psc.wb.gov.in/written_test.jsp",
            "https://wbprb.applythrunet.co.in/",
            "https://www.wbhealth.gov.in/pages/career",
            #Uttar Pradesh
            "https://uppsc.up.nic.in/CandidatePages/Notifications.aspx",
            "https://uppsc.up.nic.in/Default.aspx",
            "https://sewayojan.up.nic.in/jobs.aspx",
            "https://upsssc.gov.in/News.aspx?id=1",
            "https://upsssc.gov.in/AllNotifications.aspx",
            "https://upsssc.gov.in/Default.aspx",
            "https://uppbpb.gov.in/",
            "https://uppbpb.gov.in/Home/Notice",
            "https://uppbpb.gov.in/Home/Notice#",
            "https://uppbpb.gov.in/Home/DirectRecruitment",
            "https://uppbpb.gov.in/Home/Result",
            #ssc
            "https://ssc.nic.in/Portal/Notices",
            "https://upsc.gov.in/recruitment/recruitment-advertisements",
            #Railway
            "https://rrbahmedabad.gov.in/recruitment-statistics/",
            "arunachalpradesh.gov.in",
            #Assam
            "https://apsc.nic.in/advt_2025.php",
            "https://apscrecruitment.in/#/auth/landing",
            "https://slprbassam.in/",
            "https://job.assam.gov.in/jobs/",
            #Uttar Pradesh
            "https://uppsc.up.nic.in/CandidatePages/Notifications.aspx",
            "https://uppsc.up.nic.in/Default.aspx",
            "https://sewayojan.up.nic.in/jobs.aspx",
            "https://upsssc.gov.in/News.aspx?id=1",
            "https://upsssc.gov.in/AllNotifications.aspx",
            "https://upsssc.gov.in/Default.aspx",
            "https://uppbpb.gov.in/",
            "https://uppbpb.gov.in/Home/Notice",
            "https://uppbpb.gov.in/Home/Notice#",
            "https://uppbpb.gov.in/Home/DirectRecruitment",
            "https://uppbpb.gov.in/Home/Result"
        ]
