name: Job Monitor Bot

on:
  schedule:
    - cron: '*/40 * * * *'  # Har 40 minute run kare
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4  # ✅ v4 is better, more secure and latest

    - name: Restore sent_posts.txt (if exists)
      uses: actions/download-artifact@v4
      with:
        name: sent-posts
        path: .
      continue-on-error: true  # ✅ So first run doesn't fail if artifact not present

    - name: Set up Python
      uses: actions/setup-python@v5  # ✅ Use latest version for better compatibility
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # ✅ Better to use a single requirements file

    - name: Run monitor script
      env:
        TOKEN: ${{ secrets.TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python a.py

    - name: Upload sent_posts.txt
      if: always()  # ✅ ensures even if job fails, artifact gets uploaded
      uses: actions/upload-artifact@v4
      with:
        name: sent-posts
        path: sent_posts.txt
