name: Job Monitor Bot
on:
  schedule:
    - cron: '*/40 * * * *'  # Run every 40 minutes
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape-and-notify:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Use a stable Python version
          cache: 'pip'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found"
            exit 1
          fi

      # Optional: Clear sent_posts.txt to avoid stale data (commented out to persist data)
      # - name: Clear sent_posts.txt
      #   run: |
      #     if [ -f sent_posts.txt ]; then
      #       rm sent_posts.txt
      #       echo "Cleared sent_posts.txt"
      #     fi

      # Run the scraper script
      - name: Run monitor script
        env:
          TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python a.py

      # Upload sent_posts.txt as an artifact for debugging
      - name: Upload sent_posts.txt
        if: always()  # Upload even if the job fails
        uses: actions/upload-artifact@v4
        with:
          name: sent-posts
          path: sent_posts.txt
          retention-days: 30
