name: Job Monitor Bot

on:
  schedule:
    - cron: '*/40 * * * *'  # Run every 40 minutes
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape-and-notify:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Set safe git directory (important for GitHub-hosted runners)
      - name: Set git safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      # ✅ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      # ✅ Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests httpx beautifulsoup4 urllib3 python-dotenv PyPDF2 pdfplumber python-dateutil

      # ✅ Debug secret environment variables (optional)
      - name: Debug environment variables
        run: |
          echo "TOKEN is set: ${TOKEN:+set}"
          echo "CHAT_ID is set: ${CHAT_ID:+set}"
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      # ✅ Run your Python script
      - name: Run monitor script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python a.py

      # ✅ Commit and push updates to sent_posts.txt
      - name: Commit and push sent_posts.txt
        if: always()
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git pull --rebase origin main
          git add sent_posts.txt
          git commit -m "Update sent_posts.txt" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/pawanyadav099/website_monitor.git HEAD:main

      # ✅ Upload as an artifact (for debugging / restore)
      - name: Upload sent_posts.txt
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sent-posts
          path: sent_posts.txt
          retention-days: 30
