name: Job Monitor Bot
on:
  schedule:
    - cron: '*/40 * * * *'  # Run every 40 minutes
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape-and-notify:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Use a stable Python version
          cache: 'pip'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found, installing required packages directly"
            pip install requests httpx beautifulsoup4 urllib3 python-dotenv PyPDF2 pdfplumber python-dateutil
          fi

      # Debug environment variables
      - name: Debug environment variables
        run: |
          echo "TOKEN is set: ${TOKEN:+set}"
          echo "CHAT_ID is set: ${CHAT_ID:+set}"
        env:
          TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      # Run the scraper script
      - name: Run monitor script
        env:
          TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python a.py

      # Commit and push sent_posts.txt
      - name: Commit and push sent_posts.txt
        if: always()  # Run even if the script fails
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add sent_posts.txt
          git commit -m "Update sent_posts.txt" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload sent_posts.txt as an artifact for debugging
      - name: Upload sent_posts.txt
        if: always()  # Upload even if the job fails
        uses: actions/upload-artifact@v4
        with:
          name: sent-posts
          path: sent_posts.txt
          retention-days: 30
