name: Job Monitor Bot

on:
  schedule:
    - cron: '*/40 * * * *'  # Run every 40 minutes
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Restore sent_posts.txt from cache
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: sent_posts.txt
        key: sent-posts-cache

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests httpx beautifulsoup4 python-dateutil python-dotenv pymupdf

    - name: Run the monitoring script
      env:
        TOKEN: ${{ secrets.TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        python a.py

    - name: Save updated sent_posts.txt to cache
      uses: actions/cache/save@v4
      with:
        path: sent_posts.txt
        key: sent-posts-cache
