name: Job Monitor Bot

on:
  schedule:
    - cron: '*/40 * * * *'  # Every 40 minutes
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scrape-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found, installing required packages directly"
            pip install requests httpx beautifulsoup4 urllib3 python-dotenv PyPDF2 pdfplumber python-dateutil
          fi

      - name: Debug environment variables
        run: |
          echo "TOKEN is set: ${TOKEN:+set}"
          echo "CHAT_ID is set: ${CHAT_ID:+set}"
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Run monitor script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python a.py

      - name: Commit and push sent_posts.txt
        if: always()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git pull origin main --rebase
          git add sent_posts.txt
          git commit -m "Update sent_posts.txt" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload sent_posts.txt
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sent-posts
          path: sent_posts.txt
          retention-days: 30
